export type {
  DetectRequest,
  DetectedBlock,
  DetectResponse,
  ProcessRequest,
  Toggles,
  SimplifyLevel,
  ProcessOptions,
  RegenerateRequest,
  RegenerateTarget,
  SnippetMode,
  RegenerateContext,
  AdaptedBlock,
  SummaryResult,
  ProcessResponse,
  ProcessMeta,
  RegenerateResponse,
  RegenerateResult,
  ApiErrorCode,
  ApiError,
  OcrWordBox,
  OcrScanResponse,
} from './types';
